global:
  sendAnonymousUsage: false
api:
  insecure: true
  dashboard: true
providers:
  docker:
    watch: true
    network: reviactyl
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    watch: true
    filename: /etc/traefik/config.yml
  providersThrottleDuration: "10"
entryPoints:
  https:
    address: :443
    http:
      middlewares:
        - compress@file
